name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    paths:
      - 'WhistleCore/**'
      - 'Fuzzing/**'
      - '.clusterfuzzlite/**'
      - '.github/workflows/cflite_pr.yml'
permissions: read-all
concurrency:
  group: cflite-pr-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: swift
          sanitizer: address
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: 'code-change'
          sanitizer: address
